apiVersion: apps/v1
kind: Deployment
metadata:
  name: clinic-web
  labels:
    app: clinic-web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clinic-web-app
  template:
    metadata:
      labels:
        app: clinic-web-app
    spec:
      containers:
        - name: clinic-web
          image: "mauriciocarvalhoac/clinic-web:1.0.0"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          resources:
            limits:
              cpu: 200m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi