name: Pipeline CI/CD

on:
  push:
    branches: [ "master", "develop" , "feature/sprint082026/003-configuracao-kubernetes"]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22
    
      - name: Install dependencies
        run: npm ci
    
      - name: Build Angular
        run: npm run build -- --configuration production

      - name: Login Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build image
        run: |
          docker build \
            -t ${{ secrets.DOCKER_USERNAME }}/clinic-web:1.0.0 \
            -t ${{ secrets.DOCKER_USERNAME }}/clinic-web:1.0.0 .

      - name: Push image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/clinic-web:1.0.0
          docker push ${{ secrets.DOCKER_USERNAME }}/clinic-web:1.0.0

  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v4

      - name: Setup Helm
        uses: azure/setup-helm@v4

      - name: Configure kubeconfig
        run: |
          mkdir -p ./app/k8s

      - name: Helm Upgrade
        run: |
          helm upgrade --install clinic-web ./k8s/clinic-web/ --set image.repository=mauriciocarvalhoac/clinic-web --set image.tag=1.0.0